### PR TITLE
Fixed all the bugs I could find, and it's now working great

### PR DESCRIPTION
**Pull request by shanness**
Hi, thanks very much for this e1.31 wrapper, was just what I needed.  I've fixed it up as per the below commit message, and it's all working great now.

Fixed DMX channel handling (was out by 1 device plus 1 channel (i.e. was reading red as blue)
Fixed brightness handling (was scaling hue and all fields, i.e. changing the color, instead of just scaling the brightness), now much more accurate and rich colors
Simplfied the config section that users need to modify, changed to handle  arbitary number of bulbs instead of just 2
Simplified and refactored much of the code
Fixed the shutdown handling to be more robust and simpler

### CODE REVIEW

**Comment by shanness** [comment]
Re your README, here's the new config section I'd suggest putting in your readme.

```
########## START CONFIG SETTINGS ###########

UNIVERSE = 2 # Which dmx universe it should be listening on

first_channel = 0       # First DMX channel - 1 (to account for array position)

numb_lights = 3     # How many lights you have on your network?  All must be in the DMX data

max_bright = 0.7 # Brightness, from 0 - 1

########### END CONFIG SETTINGS ###########
```

**Comment by cpuchip** [comment]
Huh! wow I've been meaning to get back to this project, I've not fully reviewed your code, but you certainly fixed a few issues I was dealing with before I had to move on to real work. I started this project because we were looking at replacing the lights around our letter on the hill for our city with LIFX bulbs. That hasn't happened yet, but it's still in the works and all volunteer based so it's slow moving. Are you actively using this for holiday lighting or as a professional setup?

**Comment by shanness** [comment]
Hey @cpuchip , using it as a hobby thing for VJing.  Got qlcplus reacting to music, and controlling lighting and lasers in my house, and also controlling my LIFX lights using your interface.  Very performant, the lights change fast enough you can't notice the latency :)

**Comment by shanness** [comment]
The merge should clean up the code and make it easier for others to work on, and probs worth getting in to avoid duplication of bug fixes.  Also has some nice feature enhancements, like "Added config ability to proportially scale up max_bright to allow pushing lights to full bright".  I use this to override stuff and turn stuff bright if people need to see stuff ;) (i.e. over a certain brightness, it kicks in and amplifies the scaling, all configurable)

**Comment by cpuchip** [comment]
Thanks for the work! I've not had a chance to test it, and probably wont for another week, but I wanted to merge this in so I have a good base to work off of when I dig back into my Christmas lights show in a few weeks! Thanks so much for working through those bugs on my repo!

**Comment by shanness** [comment]
Move welcome!  Thanks for a very solid starting point.

**Pull request merged**
